### ISSUE TITLE
Add RNAseq linking

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/deliver#40]
Then the vague plan would be:
* fastq files would be linked to `~~/RNAseq/projects/$lims_project_id/$sample_id/$fastq_file`
  * $fastq_files would be: `${sample_id}_${flowcell}_${lane}_${readdirection}.fastq.gz`
* [x] add function is_rna to cglims.apptag
* [ ] Fast route: create an extra 'module' in deliver to be able to link rnaseq samples to above mentioned structure
* [ ] Best route: abstract away linking of samples in such way that one links a sample/project/case/flowcell and the package figures out where the samples go based on apptag

**Comment by Dilea** [comment]
Actually I would like to have all fastq's linked under the same folder:
~~/RNAseq/projects/$lims_project_id/$fastq_file

Would that be an issue?

**Comment by ingkebil** [comment]
If you don't want to wait for this, you can always run: `deliver mip --outdir ~~/RNAseq/projects/`. It'll create renamed fastq files according to `~~/RNAseq/projects/$lims_project_id/$sample_id/$fastq_file`

**Comment by emiliaol** [comment]
Not relevant anymore. Closing
