### ISSUE TITLE
cg transfer flowcell doesn't happen for reruns

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/deliver#43]

**Comment by ingkebil** [comment]
Fixed for X and 2500 in demux repo: 
https://github.com/Clinical-Genomics/demultiplexing/commit/4b4ee3dcab6ef006547ce08b8bbbbd86eb2a6b93
https://github.com/Clinical-Genomics/demultiplexing/commit/8cfd92b4f641614a3f182378cf93818670b09524
