### ISSUE TITLE
Deliver microbial fastq files

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/deliver#44]
# MWR
- no reseq
- linking all
- analysis all

# MW[G/S/M/L]
- 75% of R00X
- reseq if < 75% of req reads
- linking only if 75% reached
- analysis of linked samples

# MWX
- no reseq
- linking of all
- analysis of all

- [ ] based on the apptag, deliver fastq files after a cutoff (amount of reads) has been reached
- [ ] merge delivery of fastq files (not before analysis)

**Comment by emiliaol** [comment]
I removed the PBL label as we already have this in a user story on the backlog. Linked to this card for information.

**Comment by ingkebil** [comment]
Can you link to that user story in here as well? This issue has been mentioned in dev bioinfo#178
